# Generated by Django 5.2.6 on 2026-05-14 07:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seasonaltip_chatmessage_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[('streak', 'Streak'), ('wellness', 'Wellness'), ('diet', 'Diet'), ('dosha', 'Dosha'), ('special', 'Special')], max_length=20)),
                ('requirement_description', models.CharField(max_length=200)),
                ('is_rare', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(blank=True, max_length=100)),
                ('emoji', models.CharField(default='🌿', max_length=8)),
                ('description', models.TextField()),
                ('benefits', models.JSONField(default=list)),
                ('dosha_effects', models.JSONField(default=dict)),
                ('best_form', models.CharField(blank=True, max_length=50)),
                ('avoid_if', models.TextField(blank=True)),
                ('taste', models.CharField(blank=True, max_length=100)),
                ('common_uses', models.JSONField(default=list)),
                ('image_placeholder_color', models.CharField(default='#2D6A4F', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_swap_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meal_swaps_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_herbs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_log_date', models.DateField(blank=True, null=True)),
                ('total_logs', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PulseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('score', models.IntegerField()),
                ('grade', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Needs Attention', 'Needs Attention')], max_length=20)),
                ('json_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
