# Generated by Django 5.2.6 on 2026-05-14 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_compatibilityresult_post_comment_symptomcheck_like_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('signup', 'Sign Up'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('dosha_quiz', 'Dosha Quiz'), ('diet_generate', 'Diet Generate'), ('ai_chat', 'AI Chat'), ('symptom_check', 'Symptom Check'), ('export_pdf', 'Export PDF'), ('pulse_check', 'Pulse Check'), ('herb_view', 'Herb View'), ('community_post', 'Community Post'), ('compatibility_check', 'Compatibility Check'), ('report_generate', 'Report Generate'), ('api_request', 'API Request'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('validation_error', 'Validation Error')], default='api_request', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_path', models.CharField(blank=True, max_length=512)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_auditlo_user_id_47a824_idx'), models.Index(fields=['event_type', '-created_at'], name='api_auditlo_event_t_7feffa_idx'), models.Index(fields=['severity', '-created_at'], name='api_auditlo_severit_fdff5a_idx'), models.Index(fields=['-created_at'], name='api_auditlo_created_f26dbe_idx')],
            },
        ),
    ]
