from django.core.management.base import BaseCommand
from api.models import Herb

HERBS = [
    {
        "name": "Ashwagandha", "sanskrit_name": "Withania somnifera", "emoji": "🌱",
        "description": "Known as Indian Ginseng, Ashwagandha is the premier adaptogenic herb in Ayurveda. It builds strength, vitality, and resilience while calming the nervous system.",
        "benefits": ["Reduces stress and anxiety", "Boosts energy and stamina", "Supports immune function", "Improves sleep quality", "Enhances cognitive function"],
        "dosha_effects": {"vata": "balances", "pitta": "neutral", "kapha": "balances"},
        "best_form": "Powder or capsule with warm milk",
        "avoid_if": "Pregnancy, thyroid conditions, autoimmune diseases",
        "taste": "Bitter, astringent",
        "common_uses": ["Stress relief", "Energy boost", "Sleep support", "Muscle recovery"],
        "image_placeholder_color": "#8B7355",
    },
    {
        "name": "Turmeric", "sanskrit_name": "Curcuma longa", "emoji": "🟡",
        "description": "The golden spice of Ayurveda, Turmeric is a powerful anti-inflammatory and antioxidant. It purifies the blood, supports digestion, and promotes radiant skin.",
        "benefits": ["Powerful anti-inflammatory", "Antioxidant protection", "Supports liver health", "Aids digestion", "Promotes skin health"],
        "dosha_effects": {"vata": "balances", "pitta": "neutral", "kapha": "balances"},
        "best_form": "Powder in warm milk (Golden Milk) or food",
        "avoid_if": "Gallstones, blood thinners, pregnancy in large doses",
        "taste": "Bitter, pungent",
        "common_uses": ["Golden milk", "Cooking spice", "Wound healing", "Joint support"],
        "image_placeholder_color": "#F4A261",
    },
    {
        "name": "Triphala", "sanskrit_name": "Tri-phala", "emoji": "🫐",
        "description": "The three-fruit formula combining Amalaki, Haritaki, and Bibhitaki. Triphala is the most widely used Ayurvedic formula for gentle detoxification and digestive health.",
        "benefits": ["Gentle detoxification", "Improves digestion", "Supports eye health", "Antioxidant rich", "Balances all three doshas"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Powder with warm water before bed",
        "avoid_if": "Pregnancy, diarrhea, dehydration",
        "taste": "All six tastes",
        "common_uses": ["Digestive tonic", "Detox", "Eye wash", "Colon cleanse"],
        "image_placeholder_color": "#6B4226",
    },
    {
        "name": "Brahmi", "sanskrit_name": "Bacopa monnieri", "emoji": "🧠",
        "description": "The brain tonic of Ayurveda, Brahmi enhances memory, concentration, and cognitive function. It calms the mind and supports the nervous system.",
        "benefits": ["Enhances memory and learning", "Reduces anxiety", "Supports nervous system", "Improves concentration", "Anti-aging for the brain"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "neutral"},
        "best_form": "Powder with ghee or oil for scalp massage",
        "avoid_if": "Pregnancy, slow heart rate, thyroid medications",
        "taste": "Bitter, astringent",
        "common_uses": ["Memory support", "Stress relief", "Hair oil", "Meditation support"],
        "image_placeholder_color": "#52B788",
    },
    {
        "name": "Neem", "sanskrit_name": "Azadirachta indica", "emoji": "🌿",
        "description": "The village pharmacy of India, Neem is one of the most powerful purifying herbs. It cleanses the blood, supports skin health, and has potent antimicrobial properties.",
        "benefits": ["Blood purification", "Skin health", "Antimicrobial", "Dental health", "Liver support"],
        "dosha_effects": {"vata": "aggravates", "pitta": "balances", "kapha": "balances"},
        "best_form": "Powder, oil, or fresh leaves",
        "avoid_if": "Pregnancy, trying to conceive, children under 12",
        "taste": "Bitter",
        "common_uses": ["Skin conditions", "Dental care", "Blood purification", "Pest repellent"],
        "image_placeholder_color": "#2D6A4F",
    },
    {
        "name": "Tulsi", "sanskrit_name": "Ocimum sanctum", "emoji": "🌱",
        "description": "Holy Basil, the queen of herbs, is sacred in Ayurveda. It supports respiratory health, boosts immunity, and is a powerful adaptogen for stress.",
        "benefits": ["Respiratory support", "Immune booster", "Stress adaptogen", "Antimicrobial", "Heart health"],
        "dosha_effects": {"vata": "balances", "pitta": "neutral", "kapha": "balances"},
        "best_form": "Fresh leaves, tea, or powder",
        "avoid_if": "Blood thinners, pregnancy in large doses",
        "taste": "Pungent, bitter",
        "common_uses": ["Herbal tea", "Respiratory health", "Stress relief", "Worship"],
        "image_placeholder_color": "#40916C",
    },
    {
        "name": "Shatavari", "sanskrit_name": "Asparagus racemosus", "emoji": "🌸",
        "description": "The queen of Ayurvedic herbs for women, Shatavari nourishes and balances the female reproductive system. It is deeply nourishing and cooling.",
        "benefits": ["Female reproductive health", "Hormonal balance", "Digestive support", "Immune tonic", "Lactation support"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "aggravates"},
        "best_form": "Powder with warm milk and honey",
        "avoid_if": "Estrogen-sensitive conditions, kidney disease",
        "taste": "Sweet, bitter",
        "common_uses": ["Women's health", "Fertility support", "Digestive tonic", "Postpartum care"],
        "image_placeholder_color": "#E07A5F",
    },
    {
        "name": "Amalaki", "sanskrit_name": "Emblica officinalis", "emoji": "🟢",
        "description": "Indian Gooseberry, the richest natural source of Vitamin C. Amalaki is deeply rejuvenating, supports immunity, and is the primary ingredient in Chyawanprash.",
        "benefits": ["Highest natural Vitamin C", "Immune support", "Anti-aging", "Digestive health", "Hair and skin nourishment"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Fresh fruit, powder, or juice",
        "avoid_if": "Hypoglycemia, blood thinners",
        "taste": "Sour, sweet, astringent",
        "common_uses": ["Immunity boost", "Hair care", "Chyawanprash", "Eye health"],
        "image_placeholder_color": "#74C69D",
    },
    {
        "name": "Haritaki", "sanskrit_name": "Terminalia chebula", "emoji": "🫒",
        "description": "Called the king of medicines in Tibet, Haritaki is one of the most revered herbs in Ayurveda. It cleanses all tissues and supports longevity.",
        "benefits": ["Digestive cleanser", "Detoxification", "Cognitive support", "Anti-aging", "Wound healing"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Powder with warm water or honey",
        "avoid_if": "Pregnancy, severe dehydration, emaciation",
        "taste": "All tastes except salty",
        "common_uses": ["Digestive health", "Detox", "Eye care", "Oral health"],
        "image_placeholder_color": "#8B6914",
    },
    {
        "name": "Ginger", "sanskrit_name": "Zingiber officinale", "emoji": "🫚",
        "description": "The universal medicine of Ayurveda, Ginger kindles digestive fire (Agni), relieves nausea, and warms the body. Fresh ginger is used differently than dry.",
        "benefits": ["Kindles digestive fire", "Relieves nausea", "Anti-inflammatory", "Circulation booster", "Respiratory support"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Fresh in food/tea or dry powder",
        "avoid_if": "Pitta excess, ulcers, blood thinners",
        "taste": "Pungent",
        "common_uses": ["Digestive aid", "Nausea relief", "Warming tea", "Cooking spice"],
        "image_placeholder_color": "#D4A017",
    },
    {
        "name": "Cardamom", "sanskrit_name": "Elettaria cardamomum", "emoji": "🌿",
        "description": "The queen of spices, Cardamom is one of the few warming spices that does not aggravate Pitta. It freshens breath, aids digestion, and uplifts the mind.",
        "benefits": ["Digestive aid", "Breath freshener", "Uplifts mood", "Respiratory support", "Detoxifies caffeine"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Pods in tea or powder in food",
        "avoid_if": "Gallstones in large amounts",
        "taste": "Sweet, pungent",
        "common_uses": ["Chai tea", "Desserts", "Breath freshener", "Coffee neutralizer"],
        "image_placeholder_color": "#52B788",
    },
    {
        "name": "Cinnamon", "sanskrit_name": "Cinnamomum verum", "emoji": "🟤",
        "description": "A warming and stimulating spice, Cinnamon improves circulation, balances blood sugar, and kindles digestive fire. It is particularly beneficial for Vata and Kapha.",
        "benefits": ["Blood sugar balance", "Circulation booster", "Digestive stimulant", "Antimicrobial", "Warming"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Powder in food or tea",
        "avoid_if": "Pitta excess, pregnancy in large doses, liver disease",
        "taste": "Sweet, pungent",
        "common_uses": ["Blood sugar support", "Warming tea", "Cooking spice", "Oral health"],
        "image_placeholder_color": "#8B4513",
    },
    {
        "name": "Cumin", "sanskrit_name": "Cuminum cyminum", "emoji": "🌾",
        "description": "A digestive powerhouse, Cumin is one of the most important spices in Ayurvedic cooking. It kindles Agni, relieves gas, and supports absorption of nutrients.",
        "benefits": ["Digestive stimulant", "Relieves gas and bloating", "Iron-rich", "Antimicrobial", "Supports absorption"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Whole seeds tempered in ghee or powder",
        "avoid_if": "Excessive heat conditions",
        "taste": "Pungent, bitter",
        "common_uses": ["Cooking spice", "Digestive tea", "Kitchari", "Spice blends"],
        "image_placeholder_color": "#C8A96E",
    },
    {
        "name": "Fennel", "sanskrit_name": "Foeniculum vulgare", "emoji": "🌿",
        "description": "A cooling digestive herb, Fennel is one of the few spices that balances all three doshas. It relieves gas, freshens breath, and supports lactation.",
        "benefits": ["Relieves gas and bloating", "Cooling digestive", "Breath freshener", "Lactation support", "Eye health"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Seeds chewed after meals or as tea",
        "avoid_if": "Estrogen-sensitive conditions in large doses",
        "taste": "Sweet, pungent",
        "common_uses": ["After-meal digestive", "Herbal tea", "Cooking", "Breath freshener"],
        "image_placeholder_color": "#74C69D",
    },
    {
        "name": "Black Pepper", "sanskrit_name": "Piper nigrum", "emoji": "⚫",
        "description": "The king of spices, Black Pepper is a powerful digestive stimulant and bioavailability enhancer. It increases the absorption of other herbs, especially turmeric.",
        "benefits": ["Enhances herb absorption", "Digestive stimulant", "Respiratory support", "Antimicrobial", "Metabolism booster"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Freshly ground in food",
        "avoid_if": "Pitta excess, ulcers, inflammatory conditions",
        "taste": "Pungent",
        "common_uses": ["Cooking spice", "Turmeric enhancer", "Trikatu formula", "Respiratory support"],
        "image_placeholder_color": "#333333",
    },
    {
        "name": "Licorice", "sanskrit_name": "Glycyrrhiza glabra", "emoji": "🟫",
        "description": "Sweet and soothing, Licorice is one of the most important herbs for Pitta. It soothes inflammation, supports adrenal health, and is deeply nourishing.",
        "benefits": ["Soothes inflammation", "Adrenal support", "Respiratory health", "Digestive soothing", "Hormonal balance"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "aggravates"},
        "best_form": "Powder in tea or decoction",
        "avoid_if": "High blood pressure, kidney disease, pregnancy",
        "taste": "Sweet",
        "common_uses": ["Sore throat", "Adrenal fatigue", "Digestive soothing", "Herbal tea"],
        "image_placeholder_color": "#8B4513",
    },
    {
        "name": "Manjistha", "sanskrit_name": "Rubia cordifolia", "emoji": "🔴",
        "description": "The premier blood-purifying herb in Ayurveda, Manjistha clears heat and toxins from the blood, supports lymphatic flow, and promotes radiant skin.",
        "benefits": ["Blood purification", "Lymphatic support", "Skin health", "Anti-inflammatory", "Liver support"],
        "dosha_effects": {"vata": "neutral", "pitta": "balances", "kapha": "balances"},
        "best_form": "Powder in warm water or capsule",
        "avoid_if": "Pregnancy, kidney disease",
        "taste": "Sweet, bitter, astringent",
        "common_uses": ["Skin conditions", "Blood purification", "Lymph support", "Menstrual health"],
        "image_placeholder_color": "#C0392B",
    },
    {
        "name": "Guduchi", "sanskrit_name": "Tinospora cordifolia", "emoji": "🌿",
        "description": "Known as Amrita (divine nectar), Guduchi is one of the most powerful immune-modulating herbs. It adapts to the body's needs and supports all three doshas.",
        "benefits": ["Immune modulator", "Liver protection", "Anti-inflammatory", "Fever reducer", "Adaptogen"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Powder, juice, or decoction",
        "avoid_if": "Autoimmune conditions (consult doctor), pregnancy",
        "taste": "Bitter, astringent",
        "common_uses": ["Immunity boost", "Liver health", "Fever management", "Chronic conditions"],
        "image_placeholder_color": "#1B4332",
    },
    {
        "name": "Arjuna", "sanskrit_name": "Terminalia arjuna", "emoji": "❤️",
        "description": "The heart herb of Ayurveda, Arjuna strengthens the cardiac muscle, supports healthy blood pressure, and promotes cardiovascular health.",
        "benefits": ["Heart muscle support", "Blood pressure balance", "Cholesterol management", "Antioxidant", "Wound healing"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Powder decoction with milk (Arjuna Ksheerpaka)",
        "avoid_if": "Heart medications (consult doctor), pregnancy",
        "taste": "Astringent",
        "common_uses": ["Heart health", "Blood pressure", "Athletic performance", "Wound healing"],
        "image_placeholder_color": "#E07A5F",
    },
    {
        "name": "Shankhpushpi", "sanskrit_name": "Convolvulus pluricaulis", "emoji": "🔵",
        "description": "A powerful brain tonic, Shankhpushpi enhances memory, calms the mind, and supports the nervous system. It is particularly effective for anxiety and insomnia.",
        "benefits": ["Memory enhancement", "Anxiety relief", "Insomnia support", "Nervous system tonic", "Thyroid support"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "neutral"},
        "best_form": "Powder with milk or as syrup",
        "avoid_if": "Thyroid medications, pregnancy",
        "taste": "Bitter, astringent",
        "common_uses": ["Memory support", "Anxiety relief", "Sleep aid", "Exam preparation"],
        "image_placeholder_color": "#7B9CBF",
    },
    {
        "name": "Bhringraj", "sanskrit_name": "Eclipta alba", "emoji": "💇",
        "description": "The king of hair herbs, Bhringraj promotes hair growth, prevents premature graying, and nourishes the scalp. It also supports liver health and calms the mind.",
        "benefits": ["Hair growth promotion", "Prevents graying", "Liver support", "Calms mind", "Skin health"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "neutral"},
        "best_form": "Oil for scalp or powder internally",
        "avoid_if": "Pregnancy in large doses",
        "taste": "Bitter, pungent",
        "common_uses": ["Hair oil", "Liver tonic", "Scalp massage", "Premature graying"],
        "image_placeholder_color": "#2D6A4F",
    },
    {
        "name": "Pippali", "sanskrit_name": "Piper longum", "emoji": "🌶️",
        "description": "Long Pepper, a key component of Trikatu, Pippali is a powerful respiratory herb and digestive stimulant. It enhances bioavailability of other herbs.",
        "benefits": ["Respiratory support", "Digestive stimulant", "Bioavailability enhancer", "Metabolism booster", "Liver support"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Powder in honey or ghee",
        "avoid_if": "Pitta excess, ulcers, pregnancy",
        "taste": "Pungent",
        "common_uses": ["Respiratory health", "Trikatu formula", "Digestive support", "Metabolism"],
        "image_placeholder_color": "#C0392B",
    },
    {
        "name": "Coriander", "sanskrit_name": "Coriandrum sativum", "emoji": "🌿",
        "description": "A cooling and digestive herb, Coriander is one of the best spices for Pitta. It relieves heat, supports digestion, and has a pleasant, calming aroma.",
        "benefits": ["Cooling digestive", "Pitta pacifying", "Urinary support", "Blood sugar balance", "Detoxifying"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Fresh leaves, seeds, or powder",
        "avoid_if": "Allergies to Apiaceae family",
        "taste": "Sweet, pungent",
        "common_uses": ["Cooking spice", "Cooling tea", "Digestive support", "Urinary health"],
        "image_placeholder_color": "#52B788",
    },
    {
        "name": "Punarnava", "sanskrit_name": "Boerhavia diffusa", "emoji": "💧",
        "description": "The rejuvenating herb, Punarnava literally means 'that which renews.' It is the premier herb for kidney and urinary health, and reduces water retention.",
        "benefits": ["Kidney support", "Reduces water retention", "Liver health", "Anti-inflammatory", "Rejuvenating"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Powder decoction or capsule",
        "avoid_if": "Pregnancy, kidney disease (consult doctor)",
        "taste": "Sweet, bitter, astringent",
        "common_uses": ["Kidney health", "Edema", "Liver support", "Urinary tract"],
        "image_placeholder_color": "#7B9CBF",
    },
    {
        "name": "Vidanga", "sanskrit_name": "Embelia ribes", "emoji": "🫘",
        "description": "A powerful antiparasitic herb, Vidanga is used in Ayurveda to cleanse the digestive tract, eliminate parasites, and support digestive health.",
        "benefits": ["Antiparasitic", "Digestive cleanser", "Skin health", "Nervous system support", "Antioxidant"],
        "dosha_effects": {"vata": "balances", "pitta": "neutral", "kapha": "balances"},
        "best_form": "Powder with honey or warm water",
        "avoid_if": "Pregnancy, children without supervision",
        "taste": "Pungent, astringent",
        "common_uses": ["Parasite cleanse", "Digestive health", "Skin conditions", "Detox"],
        "image_placeholder_color": "#6B4226",
    },
    {
        "name": "Chitraka", "sanskrit_name": "Plumbago zeylanica", "emoji": "🔥",
        "description": "A powerful digestive fire kindler, Chitraka is one of the strongest herbs for stimulating Agni. It is used in many classical Ayurvedic formulas for digestion.",
        "benefits": ["Strongest Agni kindler", "Digestive stimulant", "Metabolism booster", "Liver support", "Antiparasitic"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Powder in small doses with honey",
        "avoid_if": "Pitta excess, pregnancy, ulcers, inflammatory conditions",
        "taste": "Pungent",
        "common_uses": ["Digestive fire", "Metabolism", "Liver health", "Classical formulas"],
        "image_placeholder_color": "#E07A5F",
    },
    {
        "name": "Bibhitaki", "sanskrit_name": "Terminalia bellirica", "emoji": "🫐",
        "description": "One of the three fruits of Triphala, Bibhitaki is particularly effective for Kapha conditions. It supports respiratory health, vision, and hair growth.",
        "benefits": ["Respiratory support", "Vision health", "Hair growth", "Kapha reducing", "Digestive tonic"],
        "dosha_effects": {"vata": "neutral", "pitta": "neutral", "kapha": "balances"},
        "best_form": "Powder with warm water or as part of Triphala",
        "avoid_if": "Pregnancy, Vata excess",
        "taste": "Astringent",
        "common_uses": ["Respiratory health", "Eye care", "Hair care", "Triphala formula"],
        "image_placeholder_color": "#4A90D9",
    },
    {
        "name": "Trikatu", "sanskrit_name": "Tri-katu", "emoji": "🌶️",
        "description": "The three-spice formula of Ginger, Black Pepper, and Long Pepper. Trikatu is the most powerful digestive stimulant in Ayurveda, kindling Agni and burning Ama.",
        "benefits": ["Strongest digestive stimulant", "Burns Ama (toxins)", "Metabolism booster", "Respiratory support", "Bioavailability enhancer"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Powder with honey before meals",
        "avoid_if": "Pitta excess, ulcers, pregnancy, inflammatory conditions",
        "taste": "Pungent",
        "common_uses": ["Digestive fire", "Weight management", "Respiratory health", "Detox"],
        "image_placeholder_color": "#C0392B",
    },
    {
        "name": "Pushkarmool", "sanskrit_name": "Inula racemosa", "emoji": "🌼",
        "description": "A powerful respiratory and cardiac herb, Pushkarmool is used in Ayurveda for bronchial conditions, asthma, and heart health. It clears Kapha from the lungs.",
        "benefits": ["Respiratory support", "Cardiac tonic", "Bronchial health", "Anti-inflammatory", "Kapha reducing"],
        "dosha_effects": {"vata": "balances", "pitta": "neutral", "kapha": "balances"},
        "best_form": "Powder decoction or capsule",
        "avoid_if": "Pregnancy, heart medications (consult doctor)",
        "taste": "Bitter, pungent",
        "common_uses": ["Asthma support", "Bronchitis", "Heart health", "Respiratory tonic"],
        "image_placeholder_color": "#F4D03F",
    },
    {
        "name": "Chyawanprash", "sanskrit_name": "Chyavanaprasha", "emoji": "🍯",
        "description": "The ancient Ayurvedic superfood jam, Chyawanprash is a potent blend of Amalaki and over 40 herbs. It is the premier Rasayana (rejuvenative) formula for immunity and vitality.",
        "benefits": ["Immune system booster", "Anti-aging Rasayana", "Respiratory health", "Energy and vitality", "Digestive support"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "neutral"},
        "best_form": "1-2 teaspoons with warm milk daily",
        "avoid_if": "Diabetes (high sugar content), obesity in large doses",
        "taste": "Sweet, sour, pungent",
        "common_uses": ["Daily immunity tonic", "Winter wellness", "Children's health", "Convalescence"],
        "image_placeholder_color": "#8B4513",
    },
    {
        "name": "Moringa", "sanskrit_name": "Shigru", "emoji": "🌿",
        "description": "The miracle tree of Ayurveda, Moringa is one of the most nutrient-dense plants known. It provides complete protein, vitamins, and minerals while supporting energy and immunity.",
        "benefits": ["Nutrient powerhouse", "Energy booster", "Anti-inflammatory", "Blood sugar support", "Liver protection"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Powder in smoothies or capsule",
        "avoid_if": "Pregnancy (root and bark), blood thinners",
        "taste": "Bitter, pungent",
        "common_uses": ["Nutritional supplement", "Energy boost", "Detox", "Cooking"],
        "image_placeholder_color": "#2D6A4F",
    },
    {
        "name": "Amla Oil", "sanskrit_name": "Amalaki Taila", "emoji": "💆",
        "description": "Amla oil is a traditional Ayurvedic hair and scalp treatment made from Indian Gooseberry. It nourishes hair follicles, prevents premature graying, and promotes lustrous hair growth.",
        "benefits": ["Hair growth promotion", "Prevents premature graying", "Scalp nourishment", "Dandruff control", "Cooling for scalp"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "neutral"},
        "best_form": "Oil for scalp massage",
        "avoid_if": "Scalp infections (consult doctor)",
        "taste": "Sour, sweet",
        "common_uses": ["Hair oil", "Scalp massage", "Hair conditioning", "Premature graying"],
        "image_placeholder_color": "#74C69D",
    },
    {
        "name": "Sesame", "sanskrit_name": "Tila", "emoji": "🌾",
        "description": "Sesame is one of the most important oils in Ayurveda. Sesame oil is the base for Abhyanga (self-massage) and is deeply warming, nourishing, and grounding for Vata.",
        "benefits": ["Deeply nourishing", "Grounding for Vata", "Bone health", "Skin nourishment", "Warming"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "aggravates"},
        "best_form": "Oil for Abhyanga or seeds in food",
        "avoid_if": "Pitta and Kapha excess in large amounts",
        "taste": "Sweet, bitter",
        "common_uses": ["Abhyanga massage", "Cooking oil", "Bone health", "Skin care"],
        "image_placeholder_color": "#D4A017",
    },
    {
        "name": "Mustard", "sanskrit_name": "Sarshapa", "emoji": "🟡",
        "description": "Mustard seeds are a powerful warming spice in Ayurveda. They stimulate circulation, kindle digestive fire, and are used in Panchakarma treatments for their penetrating heat.",
        "benefits": ["Circulation stimulant", "Digestive fire kindler", "Warming", "Respiratory support", "Muscle relaxant"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Seeds tempered in oil or powder",
        "avoid_if": "Pitta excess, skin inflammation, pregnancy in large doses",
        "taste": "Pungent",
        "common_uses": ["Cooking spice", "Mustard oil massage", "Respiratory steam", "Digestive support"],
        "image_placeholder_color": "#F4A261",
    },
    {
        "name": "Fenugreek", "sanskrit_name": "Methi", "emoji": "🌿",
        "description": "Fenugreek is a versatile Ayurvedic herb used as both food and medicine. It balances blood sugar, supports lactation, and is deeply nourishing for Vata conditions.",
        "benefits": ["Blood sugar balance", "Lactation support", "Digestive aid", "Anti-inflammatory", "Cholesterol management"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Seeds soaked overnight or powder",
        "avoid_if": "Pregnancy (large doses), blood thinners, diabetes medications",
        "taste": "Bitter, pungent",
        "common_uses": ["Blood sugar support", "Nursing mothers", "Cooking spice", "Hair care"],
        "image_placeholder_color": "#8B7355",
    },
    {
        "name": "Clove", "sanskrit_name": "Lavanga", "emoji": "🌰",
        "description": "Clove is a powerful warming and analgesic spice in Ayurveda. It is used for dental pain, digestive issues, and respiratory conditions. Its penetrating quality clears Kapha.",
        "benefits": ["Natural analgesic", "Dental health", "Digestive stimulant", "Antimicrobial", "Respiratory support"],
        "dosha_effects": {"vata": "balances", "pitta": "aggravates", "kapha": "balances"},
        "best_form": "Whole cloves in food or clove oil",
        "avoid_if": "Pitta excess, pregnancy in large doses, blood thinners",
        "taste": "Pungent, bitter",
        "common_uses": ["Dental pain", "Chai spice", "Digestive support", "Oral health"],
        "image_placeholder_color": "#6B4226",
    },
    {
        "name": "Saffron", "sanskrit_name": "Kumkuma", "emoji": "🌸",
        "description": "The most precious spice in Ayurveda, Saffron is a powerful Ojas (vital essence) builder. It uplifts the mind, supports reproductive health, and promotes radiant skin.",
        "benefits": ["Ojas builder", "Mood enhancer", "Reproductive health", "Skin radiance", "Anti-depressant"],
        "dosha_effects": {"vata": "balances", "pitta": "balances", "kapha": "balances"},
        "best_form": "Soaked in warm milk or water",
        "avoid_if": "Pregnancy in large doses, blood thinners",
        "taste": "Sweet, bitter",
        "common_uses": ["Golden milk", "Reproductive health", "Skin care", "Mood support"],
        "image_placeholder_color": "#E9C46A",
    },
    {
        "name": "Vetiver", "sanskrit_name": "Ushira", "emoji": "🌾",
        "description": "Vetiver root is one of the most cooling herbs in Ayurveda. It pacifies Pitta, relieves heat conditions, and is used in summer to cool the body and calm the mind.",
        "benefits": ["Deeply cooling", "Pitta pacifying", "Stress relief", "Skin cooling", "Fever reducer"],
        "dosha_effects": {"vata": "neutral", "pitta": "balances", "kapha": "neutral"},
        "best_form": "Powder in water or as cooling drink",
        "avoid_if": "Vata excess, cold conditions",
        "taste": "Bitter, sweet",
        "common_uses": ["Summer cooling drink", "Skin care", "Stress relief", "Fever management"],
        "image_placeholder_color": "#52B788",
    },
    {
        "name": "Musta", "sanskrit_name": "Cyperus rotundus", "emoji": "🌿",
        "description": "Musta (Nutgrass) is a powerful digestive and fever-reducing herb. It is particularly effective for Pitta and Kapha conditions, supporting digestion and clearing heat.",
        "benefits": ["Digestive support", "Fever reducer", "Anti-inflammatory", "Pitta pacifying", "Menstrual support"],
        "dosha_effects": {"vata": "neutral", "pitta": "balances", "kapha": "balances"},
        "best_form": "Powder decoction or capsule",
        "avoid_if": "Pregnancy, Vata excess",
        "taste": "Bitter, pungent, astringent",
        "common_uses": ["Digestive health", "Fever management", "Menstrual support", "Detox"],
        "image_placeholder_color": "#40916C",
    },
]


class Command(BaseCommand):
    help = "Seed the database with Ayurvedic herb data"

    def add_arguments(self, parser):
        parser.add_argument("--clear", action="store_true")

    def handle(self, *args, **options):
        if options.get("clear"):
            Herb.objects.all().delete()
            self.stdout.write("Cleared existing herbs.")

        created = 0
        for h in HERBS:
            obj, was_created = Herb.objects.get_or_create(
                name=h["name"],
                defaults=h,
            )
            if was_created:
                created += 1

        self.stdout.write(self.style.SUCCESS(f"Seeded {created} herbs ({Herb.objects.count()} total)."))
