import type { Config } from "tailwindcss";

export default {
  darkMode: 'class',
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: '#0f5238',
          light: '#52B788',
          dark: '#1B4332',
        },
        accent: {
          DEFAULT: '#E9C46A',
          dark: '#F4A261',
        },
        surface: {
          DEFAULT: '#FEFAE0',
          dark: '#F5ECD7',
        },
        dosha: {
          vata: '#7B9CBF',
          pitta: '#E07A5F',
          kapha: '#6B8F71',
        },
        "text-primary": "#1A1A2E",
        "text-muted": "#6B7280",
        secondary: {
          DEFAULT: "#765a05",
          foreground: "#ffffff",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Modern Ayurvedic Harmony additions
        "surface-dim": '#dedbc2',
        "surface-bright": '#fefae0',
        "surface-container-lowest": '#ffffff',
        "surface-container-low": '#f8f4db',
        "surface-container": '#f2efd5',
        "surface-container-high": '#ede9cf',
        "surface-container-highest": '#e7e3ca',
        "on-surface": '#1d1c0d',
        "on-surface-variant": '#404943',
        "inverse-surface": '#323120',
        "inverse-on-surface": '#f5f1d8',
        outline: '#707973',
        "outline-variant": '#bfc9c1',
        "surface-tint": '#2c694e',
        "on-primary": '#ffffff',
        "primary-container": '#2d6a4f',
        "on-primary-container": '#a8e7c5',
        "inverse-primary": '#95d4b3',
        "on-secondary": '#ffffff',
        "secondary-container": '#ffd87c',
        "on-secondary-container": '#795d08',
        tertiary: '#274f3d',
        "on-tertiary": '#ffffff',
        "tertiary-container": '#3f6754',
        "on-tertiary-container": '#b8e3cb',
        error: '#ba1a1a',
        "on-error": '#ffffff',
        "error-container": '#ffdad6',
        "on-error-container": '#93000a',
        "primary-fixed": '#b1f0ce',
        "primary-fixed-dim": '#95d4b3',
        "on-primary-fixed": '#002114',
        "on-primary-fixed-variant": '#0e5138',
        "secondary-fixed": '#ffdf96',
        "secondary-fixed-dim": '#e7c268',
        "on-secondary-fixed": '#251a00',
        "on-secondary-fixed-variant": '#5a4400',
        "tertiary-fixed": '#c1ecd4',
        "tertiary-fixed-dim": '#a5d0b9',
        "on-tertiary-fixed": '#002114',
        "on-tertiary-fixed-variant": '#274e3d',
        "surface-variant": '#e7e3ca',
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-down": {
          "0%": { opacity: "0", transform: "translateY(-16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-8px) rotate(3deg)" },
        },
        "float-delayed": {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-10px) rotate(-2deg)" },
        },
        "breath": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.8", filter: "drop-shadow(0 0 10px rgba(15, 82, 56, 0.3))" },
          "50%": { transform: "scale(1.05)", opacity: "1", filter: "drop-shadow(0 0 20px rgba(15, 82, 56, 0.6))" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "page-enter": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
        fadeDown: {
          from: { opacity: "0", transform: "translateY(-16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        growLine: {
          from: { width: "0" },
          to: { width: "100%" },
        },
        growBar: {
          from: { transform: "scaleX(0)" },
          to: { transform: "scaleX(1)" },
        },
        shimmer: {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(100%)" },
        },
        floatPitta: {
          "0%, 100%": { transform: "translate(-50%, -50%) translateY(0px)" },
          "50%": { transform: "translate(-50%, -50%) translateY(-14px)" },
        },
        floatVata: {
          "0%, 100%": { transform: "translateY(0px) rotate(-3deg)" },
          "50%": { transform: "translateY(-10px) rotate(-3deg)" },
        },
        floatKapha: {
          "0%, 100%": { transform: "translateY(0px) rotate(3deg)" },
          "50%": { transform: "translateY(-12px) rotate(3deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out",
        "fade-in-down": "fade-in-down 0.5s ease-out",
        "float": "float 3s ease-in-out infinite",
        "float-slow": "float-slow 5s ease-in-out infinite",
        "float-delayed": "float-delayed 4s ease-in-out infinite 1s",
        "breath": "breath 6s ease-in-out infinite",
        "slide-in-right": "slide-in-right 0.5s ease-out",
        "slide-in-left": "slide-in-left 0.5s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "page-enter": "page-enter 0.3s ease-out",
        "spin-slow": "spin-slow 20s linear infinite",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "float-pitta": "floatPitta 4s ease-in-out infinite",
        "float-vata": "floatVata 5s ease-in-out 0.5s infinite",
        "float-kapha": "floatKapha 4.5s ease-in-out 1s infinite",
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #2D6A4F, #52B788)",
        "gradient-primary-dark": "linear-gradient(135deg, #1B4332, #2D6A4F)",
        "gradient-accent": "linear-gradient(135deg, #E9C46A, #F4A261)",
        "gradient-surface": "linear-gradient(180deg, #FEFAE0, #F5ECD7)",
        "gradient-hero": "linear-gradient(135deg, #1B4332 0%, #2D6A4F 50%, #52B788 100%)",
        "gradient-wellness": "linear-gradient(135deg, #2D6A4F, #52B788)",
        "gradient-calm": "linear-gradient(180deg, rgba(254,250,224,0.5), rgba(245,236,215,0.5))",
      },
      boxShadow: {
        "wellness": "0 10px 40px -8px rgba(45,106,79,0.25)",
        "wellness-lg": "0 20px 60px -12px rgba(45,106,79,0.3)",
        "soft": "0 4px 20px -4px rgba(45,106,79,0.12)",
        "accent": "0 8px 30px -6px rgba(233,196,106,0.4)",
        "card": "0 2px 16px -2px rgba(26,26,46,0.08)",
        "card-hover": "0 8px 32px -4px rgba(26,26,46,0.14)",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  safelist: [
    "bg-primary/4",
    "bg-primary/8",
    "bg-primary/10",
    "bg-primary/15",
    "border-primary/8",
    "border-primary/10",
    "border-primary/12",
    "border-primary/15",
    "border-primary/20",
    "border-primary/25",
    "border-primary/30",
    "border-primary/40",
    "text-dosha-vata",
    "text-dosha-pitta",
    "text-dosha-kapha",
    "bg-dosha-vata",
    "bg-dosha-pitta",
    "bg-dosha-kapha",
    "bg-dosha-vata/10",
    "bg-dosha-pitta/10",
    "bg-dosha-kapha/10",
    "bg-dosha-vata/15",
    "bg-dosha-pitta/15",
    "bg-dosha-kapha/15",
    "bg-dosha-vata/20",
    "bg-dosha-pitta/20",
    "bg-dosha-kapha/20",
    "border-dosha-vata/20",
    "border-dosha-pitta/20",
    "border-dosha-kapha/20",
    "border-dosha-vata/25",
    "border-dosha-pitta/25",
    "border-dosha-kapha/25",
    "border-dosha-vata/30",
    "border-dosha-pitta/30",
    "border-dosha-kapha/30",
  ],
} satisfies Config;
